name: Build and Test

on:
  push:
    branches:
      - '**'
  pull_request:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git g++ make cmake libgmp-dev libreadline-dev libncurses-dev libboost-all-dev zlib1g-dev libzstd-dev

    - name: Build and install SoPlex
      run: |
        git clone https://github.com/scipopt/soplex.git
        mkdir soplex/build && cd soplex/build
        cmake ..
        make -j

    - name: Build and run tests
      run: |
        mkdir build && build
        cmake .. -DSOPLEX_DIR=../soplex/build
        make -j
        ctest